name: Build NSIS Plugin Dll's and Artifacts
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - '*.sln'
    - '*.vcproj'
    - '*.vcxproj'
    - 'Src/**.c'
    - 'Src/**.h'
    - 'Src/**.lib'
  push:
    paths:
    - '*.sln'
    - '*.vcproj'
    - '*.vcxproj'
    - 'Src/**.c'
    - 'Src/**.h'
    - 'Src/**.lib'
jobs:
  build:
    runs-on: windows-latest
    steps:
    # checkout code from repo
    - name: Checkout
      uses: actions/checkout@v1
    # use msbuild to build the solution
    - name: Build Dll's
      run: |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe EnVar.sln"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" EnVar.sln
    # Prepare distribution folder
    - name: Create Distribution
      if: success()
      run: |
        echo "Copy source files to Contrib"
        mkdir Dist\Contrib\EnVar"
        xcopy Src" Dist\Contrib\EnVar\Src" /E
        xcopy EnVar.*" Dist\Contrib\EnVar"
        echo "Copy doc files to Docs"
        mkdir Dist\Docs\EnVar"
        copy LICENSE" Dist\Docs\EnVar"
        copy README.md" Dist\Docs\EnVar"
        echo "Copy dll's to Plugins"
        mkdir Dist\Plugins\amd64-unicode"
        copy Lib\x64\Release Unicode\EnVar.dll" Dist\Plugins\amd64-unicode"
        mkdir Dist\Plugins\x86-ansi"
        copy Lib\Win32\Release\EnVar.dll" Dist\Plugins\x86-ansi"
        mkdir Dist\Plugins\x86-unicode"
        copy Lib\Win32\Release Unicode\EnVar.dll" Dist\Plugins\x86-unicode"
    # Publish Distribution Artifact
    - name: Publish Distribution Artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: EnVar-plugin-${{ github.ref }}
        path: Dist
    # Publish Library Artifact
    - name: Publish Library Artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: lib-${{ github.ref }}
        path: Lib
