name: Build NSIS Plugin Dll's and Artifacts
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '*.sln'
      - '*.vcproj'
      - '*.vcxproj'
      - 'Bin/Build.ps1'
      - 'Src/**.c'
      - 'Src/**.h'
      - 'Src/**.lib'
      - 'Tests/plugin_test.nsi'
  push:
    branches:    
      - main
      - master # remove onces migrated to main
    tags:        
      - v*
    paths:
      - '*.sln'
      - '*.vcproj'
      - '*.vcxproj'
      - 'Bin/Build.ps1'
      - 'Src/**.c'
      - 'Src/**.h'
      - 'Src/**.lib'
      - 'Tests/plugin_test.nsi'
jobs:
  build:
    name: Build Dll's
    runs-on: windows-latest
    steps:
      # checkout code from repo
      - name: Checkout
        uses: actions/checkout@v1
      # Install Modules
      - name: Setup Build Script
        run: Install-Module -Name Invoke-MsBuild -Force
      # use msbuild to build the solution
      - name: Build Plugin
        run: Bin\Build.ps1 New-Build
      # upload artifacts
      - name: Publish Lib Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Lib-${{ github.sha }}
          path: Lib
      - name: Publish Obj Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Obj-${{ github.sha }}
          path: Obj
      # Prepare distribution folder
      - name: Create Distribution
        run: Bin\Build.ps1 New-Distribution, Compress-Distribution
      # Publish Distribution Artifact
      - name: Publish Dist Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Dist-${{ github.sha }}
          path: Dist
      - name: Publish Data Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Data-${{ github.sha }}
          path: Data
      # Deploy plugin
      - name: Deploy plugin
        run: Bin\Build.ps1 Deploy-Plugin
      # Build PluginTest
      - name: Build PluginTest
        run: Bin\Build.ps1 Build-PluginTest
      # Publish PluginTest Artifact
      - name: Publish PluginTest Artifact
        uses: actions/upload-artifact@v1
        with:
          name: PluginTest-${{ github.sha }}
          path: Tests\PluginTest.exe
      # Test Plugin
      - name: Test Plugin
        run: Bin\Build.ps1 Start-PluginTest
      # Publish PluginTest Log Artifact
      - name: Publish PluginTest Log Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: PluginTest-Log-${{ github.sha }}
          path: Tests\PluginTest.log
