name: Build NSIS Plugin Dll's and Artifacts
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
    - '*.sln'
    - '*.vcproj'
    - '*.vcxproj'
    - 'Src/**.c'
    - 'Src/**.h'
    - 'Src/**.lib'
  push:
    paths:
    - '*.sln'
    - '*.vcproj'
    - '*.vcxproj'
    - 'Src/**.c'
    - 'Src/**.h'
    - 'Src/**.lib'
jobs:
  build:
    runs-on: windows-latest
    steps:
      # checkout code from repo
      - name: Checkout
        uses: actions/checkout@v1
      # use msbuild to build the solution
      - name: Build Dll's
        run: |
          rem Get-Variable | Write-Output
          set
          echo "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe %GITHUB_WORKSPACE%\EnVar.sln"
          echo "${ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe ${GITHUB_WORKSPACE}\EnVar.sln"
          "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" %GITHUB_WORKSPACE%\EnVar.sln
        shell: cmd
      # Prepare distribution folder
      - name: Create Distribution
        if: success()
        run: |
          echo "Copy source files to Contrib"
          mkdir "%GITHUB_WORKSPACE%\Dist\Contrib\EnVar"
          xcopy "%GITHUB_WORKSPACE%\Src" "%GITHUB_WORKSPACE%\Dist\Contrib\EnVar\Src" /E
          xcopy "%GITHUB_WORKSPACE%\EnVar.*" "%GITHUB_WORKSPACE%\Dist\Contrib\EnVar"
          echo "Copy doc files to Docs"
          mkdir "%GITHUB_WORKSPACE%\Dist\Docs\EnVar"
          copy "%GITHUB_WORKSPACE%\LICENSE" "%GITHUB_WORKSPACE%\Dist\Docs\EnVar"
          copy "%GITHUB_WORKSPACE%\README.md" "%GITHUB_WORKSPACE%\Dist\Docs\EnVar"
          echo "Copy dll's to Plugins"
          mkdir "%GITHUB_WORKSPACE%\Dist\Plugins\amd64-unicode"
          copy "%GITHUB_WORKSPACE%\Lib\x64\Release Unicode\EnVar.dll" "%GITHUB_WORKSPACE%\Dist\Plugins\amd64-unicode"
          mkdir "%GITHUB_WORKSPACE%\Dist\Plugins\x86-ansi"
          copy "%GITHUB_WORKSPACE%\Lib\Win32\Release\EnVar.dll" "%GITHUB_WORKSPACE%\Dist\Plugins\x86-ansi"
          mkdir "%GITHUB_WORKSPACE%\Dist\Plugins\x86-unicode"
          copy "%GITHUB_WORKSPACE%\Lib\Win32\Release Unicode\EnVar.dll" "%GITHUB_WORKSPACE%\Dist\Plugins\x86-unicode"
        shell: cmd
      # Publish Distribution Artifact
      - name: Publish Distribution Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: EnVar-plugin-${{ github.ref }}
          path: Dist
      # Publish Library Artifact
      - name: Publish Library Artifact
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: lib-${{ github.ref }}
          path: Lib
